### PR TITLE
[a11y] Trap keyboard focus in DialogModal

### PR DESCRIPTION
**Pull request by ipc103**
[Asana Task](https://app.asana.com/0/1182623358122135/1182893274583740)

When the `DialogModal` is open, we should lock the focus inside of the modal to make it easy for keyboard users to interact with. This PR accomplishes this by using the [FocusScope](https://react-spectrum.adobe.com/react-aria/FocusScope.html) component from react-aria. We automatically trap focus inside the modal when it opens, and return focus to the last focused element when it closes. In addition, if a close icon is present, we allow the user to dismiss the modal using the Escape key. 

Screen Shot 2020-07-22 at 2 47 57 PM

### CODE REVIEW

**Comment by michaeljaltamirano** [comment]
> In addition, if a close icon is present, we allow the user to dismiss the modal using the Escape key.

Is this informed by any sort of WCAG or WAI-ARIA spec, or just our own flavor?

**Comment by ipc103** [comment]
@michaeljaltamirano - just our own flavor. I haven't seen a spec that explicitly requires that the Escape key dismisses modals, and I can imagine cases where we might require an explicit confirmation before returning to the rest of the page. If that seems too restrictive, definitely happy to apply the escape key behavior for all instances.

**Comment by michaeljaltamirano** [comment]
> @michaeljaltamirano - just our own flavor. I haven't seen a spec that explicitly requires that the Escape key dismisses modals, and I can imagine cases where we might require an explicit confirmation before returning to the rest of the page. If that seems too restrictive, definitely happy to apply the escape key behavior for all instances.

I'm not too familiar with the DialogModal development but I would venture to guess that the more restrictive version requires an explicit yes/no from a patient, so I think it's fine as is. Great use of the tool.

**Comment by ipc103** [comment]
Super interesting! The component felt so intuitive to use and solved such an important problem that I almost cried 😂

**Pull request merged**
