### PR TITLE
Feature/upgrade dependencies

### PR DESCRIPTION
**Pull request by cmgmyr**
https://app.asana.com/0/1156667858696586/1156075392616963

This PR upgrades a handful of dependencies:

- ~~Storybook (and related)~~
- Jest (and related)
- Enzyme (and related)

The current security alert for handlebars is tied to the past version of Jest. After the Jest upgrade handlebars is no longer a dependency.

### CODE REVIEW

**Comment by michaeljaltamirano** [comment]
> This PR upgrades a handful of dependencies:
> 
> * Storybook (and related)
> * Jest (and related)
> * Enzyme (and related)
> 
> The current security alert for handlebars is tied to the past version of Jest. After the Jest upgrade handlebars is no longer a dependency.

Is there an Asana ticket for these changes?

I think that the `storybook` updates and the test dependency updates should be separate PRs. The functionality changes in minor `storybook` releases is actually pretty much always fairly major: there are migration guides for both migrating for [`5.1.x to 5.1.10`](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-51x-to-5110), [`5.1.x to 5.2.x`](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-51x-to-52x), and [`5.2.x to 5.3.x`](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-52x-to-53x). Do any of these apply?

**Comment by cmgmyr** [comment]
@michaeljaltamirano I added the asana ticket. I'll go ahead and break off the storybook one to a different PR. I didn't see any issues with running storybook, but I'll give it another look through 👍

**Comment by michaeljaltamirano** [comment]
> @michaeljaltamirano I added the asana ticket. I'll go ahead and break off the storybook one to a different PR. I didn't see any issues with running storybook, but I'll give it another look through 👍

All good! It has just been my experience that Storybook, due to all its functionality and plugins, rarely has straight-forward upgrades, and it looks like at least [one migration item](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#source-loader) applies to us. (Though it is not a breaking change, we should still make updates accordingly)

**Comment by snags88** [comment]
@cmgmyr It looks like the build on Heroku is failing https://dashboard.heroku.com/apps/curology-radiance-pr-173/activity/builds/c208806c-4373-4bdc-b920-7adaf66788f6. Not sure if this was already existing or there's something we need to fix related to this PR

**Comment by cmgmyr** [comment]
Yes, Michael pointed out via slack that we might have an issue with our fork `PocketDerm/create-index#master`

**Comment by snags88** [comment]
ah gotcha. Yeah I forked that to get it working with how we wanted to build our icon files. Possible that we just roll out our own. I forget how complex that library is.

**Pull request merged**
