### PR TITLE
Add cleanser moisturizer duo glyph

### PR DESCRIPTION
**Pull request by irislam94**
Adds a cleanser moisturizer duo glyph for the rewards callout

[Figma](https://www.figma.com/file/Nw5k99h9wplaSvlqw3sEEX/Referral-Existing-Users-P0?node-id=529%3A2947)

Screen Shot 2022-04-19 at 2 30 48 PM

### CODE REVIEW

**Review by michaeljaltamirano — CHANGES_REQUESTED** [review]
The dimensions look good! I went ahead and approved it on Chromatic: https://www.chromatic.com/build?appId=5f6e46f1e7081000221523cf&number=1771

The "requested change" is not a code one, but an organizational one: The glyph is in a feature file, but we should make sure it is added to the Radiance glyph documentation as well: [here's the link to the Figma file](https://www.figma.com/file/RZIO3wuO5Uk7sPZoXstAuXIA/Radiance-UI?node-id=2300%3A18242). I think the designer should know how to take it from there, provided the name. Feel free to re-tag me for review once it is documented!

**Review by michaeljaltamirano — APPROVED** [review]
LGTM! We can cut this as a `26.3.0` release if it is going out urgently 🙂

**Comment by michaeljaltamirano** [comment]
@irislam94 It looks like the yellow icon might not update unless the branch builds again, but it looks fine to merge in.

**Comment by irislam94** [comment]
@michaeljaltamirano gotcha, thank you!

**Pull request merged**
